// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new pet API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for pet API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AddPet adds a new pet to the store
*/
func (a *Client) AddPet(params *AddPetParams, authInfo runtime.ClientAuthInfoWriter) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddPetParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "addPet",
		Method:             "POST",
		PathPattern:        "/pet",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/xml"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AddPetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil

}

/*
DeletePet deletes a pet
*/
func (a *Client) DeletePet(params *DeletePetParams, authInfo runtime.ClientAuthInfoWriter) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeletePetParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deletePet",
		Method:             "DELETE",
		PathPattern:        "/pet/{petId}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeletePetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil

}

/*
FindPetsByStatus finds pets by status

Multiple status values can be provided with comma separated strings
*/
func (a *Client) FindPetsByStatus(params *FindPetsByStatusParams, authInfo runtime.ClientAuthInfoWriter) (*FindPetsByStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewFindPetsByStatusParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "findPetsByStatus",
		Method:             "GET",
		PathPattern:        "/pet/findByStatus",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &FindPetsByStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*FindPetsByStatusOK), nil

}

/*
FindPetsByTags finds pets by tags

Muliple tags can be provided with comma separated strings. Use         tag1, tag2, tag3 for testing.
*/
func (a *Client) FindPetsByTags(params *FindPetsByTagsParams, authInfo runtime.ClientAuthInfoWriter) (*FindPetsByTagsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewFindPetsByTagsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "findPetsByTags",
		Method:             "GET",
		PathPattern:        "/pet/findByTags",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &FindPetsByTagsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*FindPetsByTagsOK), nil

}

/*
GetPetByID finds pet by ID

Returns a single pet
*/
func (a *Client) GetPetByID(params *GetPetByIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetPetByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPetByIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getPetById",
		Method:             "GET",
		PathPattern:        "/pet/{petId}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPetByIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetPetByIDOK), nil

}

/*
UpdatePet updates an existing pet
*/
func (a *Client) UpdatePet(params *UpdatePetParams, authInfo runtime.ClientAuthInfoWriter) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdatePetParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updatePet",
		Method:             "PUT",
		PathPattern:        "/pet",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/xml"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdatePetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil

}

/*
UpdatePetWithForm updates a pet in the store with form data
*/
func (a *Client) UpdatePetWithForm(params *UpdatePetWithFormParams, authInfo runtime.ClientAuthInfoWriter) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdatePetWithFormParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updatePetWithForm",
		Method:             "POST",
		PathPattern:        "/pet/{petId}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/x-www-form-urlencoded"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdatePetWithFormReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil

}

/*
UploadFile uploads an image
*/
func (a *Client) UploadFile(params *UploadFileParams, authInfo runtime.ClientAuthInfoWriter) (*UploadFileOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUploadFileParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "uploadFile",
		Method:             "POST",
		PathPattern:        "/pet/{petId}/uploadImage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UploadFileReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UploadFileOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
